# Generated by Django 5.2.17 on 2026-09-17 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField()),
            ],
            options={
                'verbose_name': 'System Clock',
            },
        ),
        migrations.CreateModel(
            name='OutboxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_entries', to='customers.customer')),
            ],
            options={
                'ordering': ['-delivery_date'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'delivery_date'), name='unique_outbox_per_customer_per_day')],
            },
        ),
    ]
