# Generated by Django 5.2.17 on 2026-09-17 11:20

from datetime import date
from django.db import migrations

def seed_system_clock(apps, schema_editor):
    SystemClock = apps.get_model('notifications', 'SystemClock')
    SystemClock.objects.create(id=1, current_date=date.today())

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_system_clock),
    ]
