# Generated by Django 5.2.17 on 2026-09-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('ownership_from', models.DateField()),
                ('ownership_to', models.DateField()),
                ('total_weekdays_in_segment', models.IntegerField()),
                ('paused_weekdays', models.IntegerField()),
                ('delivered_weekdays', models.IntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=8)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='customers.customer')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-billing_month', '-generated_at'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'customer', 'billing_month'), name='unique_billing_per_customer_per_sub_per_month')],
            },
        ),
    ]
