# Generated by Django 5.2.17 on 2026-09-17 11:20

from datetime import date
from django.db import migrations

def seed_plans(apps, schema_editor):
    Plan = apps.get_model('plans', 'Plan')
    Plan.objects.create(name='Basic Tiffin', monthly_price='100.00', effective_from=date.today())
    Plan.objects.create(name='Premium Tiffin', monthly_price='150.00', effective_from=date.today())

class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_plans),
    ]
